// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: getcdv3/getcdv3.proto

package pb_getcdv3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PeerReq) Reset() {
	*x = PeerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getcdv3_getcdv3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerReq) ProtoMessage() {}

func (x *PeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_getcdv3_getcdv3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerReq.ProtoReflect.Descriptor instead.
func (*PeerReq) Descriptor() ([]byte, []int) {
	return file_getcdv3_getcdv3_proto_rawDescGZIP(), []int{0}
}

type PeerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *PeerResp) Reset() {
	*x = PeerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getcdv3_getcdv3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResp) ProtoMessage() {}

func (x *PeerResp) ProtoReflect() protoreflect.Message {
	mi := &file_getcdv3_getcdv3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResp.ProtoReflect.Descriptor instead.
func (*PeerResp) Descriptor() ([]byte, []int) {
	return file_getcdv3_getcdv3_proto_rawDescGZIP(), []int{1}
}

func (x *PeerResp) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_getcdv3_getcdv3_proto protoreflect.FileDescriptor

var file_getcdv3_getcdv3_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x65, 0x74, 0x63, 0x64, 0x76, 0x33, 0x2f, 0x67, 0x65, 0x74, 0x63, 0x64, 0x76,
	0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x65, 0x74, 0x63, 0x64, 0x76, 0x33,
	0x22, 0x09, 0x0a, 0x07, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x1e, 0x0a, 0x08, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x32, 0x36, 0x0a, 0x04, 0x70,
	0x65, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x10,
	0x2e, 0x67, 0x65, 0x74, 0x63, 0x64, 0x76, 0x33, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x67, 0x65, 0x74, 0x63, 0x64, 0x76, 0x33, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x77, 0x6c, 0x6f, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x74, 0x63,
	0x64, 0x76, 0x33, 0x2f, 0x67, 0x65, 0x74, 0x63, 0x64, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x65, 0x74, 0x63, 0x64, 0x76, 0x33, 0x3b, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x74,
	0x63, 0x64, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getcdv3_getcdv3_proto_rawDescOnce sync.Once
	file_getcdv3_getcdv3_proto_rawDescData = file_getcdv3_getcdv3_proto_rawDesc
)

func file_getcdv3_getcdv3_proto_rawDescGZIP() []byte {
	file_getcdv3_getcdv3_proto_rawDescOnce.Do(func() {
		file_getcdv3_getcdv3_proto_rawDescData = protoimpl.X.CompressGZIP(file_getcdv3_getcdv3_proto_rawDescData)
	})
	return file_getcdv3_getcdv3_proto_rawDescData
}

var file_getcdv3_getcdv3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getcdv3_getcdv3_proto_goTypes = []interface{}{
	(*PeerReq)(nil),  // 0: getcdv3.PeerReq
	(*PeerResp)(nil), // 1: getcdv3.PeerResp
}
var file_getcdv3_getcdv3_proto_depIdxs = []int32{
	0, // 0: getcdv3.peer.GetAddr:input_type -> getcdv3.PeerReq
	1, // 1: getcdv3.peer.GetAddr:output_type -> getcdv3.PeerResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getcdv3_getcdv3_proto_init() }
func file_getcdv3_getcdv3_proto_init() {
	if File_getcdv3_getcdv3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getcdv3_getcdv3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getcdv3_getcdv3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getcdv3_getcdv3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getcdv3_getcdv3_proto_goTypes,
		DependencyIndexes: file_getcdv3_getcdv3_proto_depIdxs,
		MessageInfos:      file_getcdv3_getcdv3_proto_msgTypes,
	}.Build()
	File_getcdv3_getcdv3_proto = out.File
	file_getcdv3_getcdv3_proto_rawDesc = nil
	file_getcdv3_getcdv3_proto_goTypes = nil
	file_getcdv3_getcdv3_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PeerClient is the client API for Peer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeerClient interface {
	GetAddr(ctx context.Context, in *PeerReq, opts ...grpc.CallOption) (*PeerResp, error)
}

type peerClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerClient(cc grpc.ClientConnInterface) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) GetAddr(ctx context.Context, in *PeerReq, opts ...grpc.CallOption) (*PeerResp, error) {
	out := new(PeerResp)
	err := c.cc.Invoke(ctx, "/getcdv3.peer/GetAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServer is the server API for Peer service.
type PeerServer interface {
	GetAddr(context.Context, *PeerReq) (*PeerResp, error)
}

// UnimplementedPeerServer can be embedded to have forward compatible implementations.
type UnimplementedPeerServer struct {
}

func (*UnimplementedPeerServer) GetAddr(context.Context, *PeerReq) (*PeerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddr not implemented")
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_GetAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).GetAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getcdv3.peer/GetAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).GetAddr(ctx, req.(*PeerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "getcdv3.peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddr",
			Handler:    _Peer_GetAddr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getcdv3/getcdv3.proto",
}
